### ISSUE TITLE
Cannot deploy on self-signed certificate

### ISSUE THREAD

**Issue by compiaffe** [lionelvillard/openwhisk-wskp#1]
When working on a test setup of openwhisk with only self-signed certificates I cannot deploy with 

`wskp deploy -i openwhisk.yaml`
due to :
```
Error: missing configuration file
```

or `wskp deploy openwhisk.yaml -i`
due to:
```
not ok: OpenWhiskError: Unknown Error From API: self signed certificate
```

Creating an `alias wsk="wsk -i" in the .zshrc/.bashrc (and resourcing the file) does not solve this issue.
Is there a way to disable the certificate checking in wskp?

**Comment by lionelvillard** [comment]
`-i` should work but apparently it is broken.

`wskp` is now deprecated. I recommend using [wskdeploy](https://github.com/apache/incubator-openwhisk-wskdeploy)

@compiaffe

**Comment by compiaffe** [comment]
Thanks, I will use wskdeploy from now.
